#!/usr/bin/env bash

echo "1. Build"
echo "2. Deploy"
echo "3. Exit"
read -p "Choose option 1-4: " ACTION

## deploy the app
if [[ $ACTION == "2" ]]; then
    chown -R www-data: *

    docker compose up -d

    sleep 30

    source .env

    docker exec -i {$DB_HOST} mysql -u{$DB_USER} -p{$DB_PASS} {$DB_NAME} < ./install/db.sql
    while [ $? -eq 1 ]; do
        docker exec -i {$DB_HOST} mysql -u{$DB_USER} -p{$DB_PASS} {$DB_NAME} < ./install/db.sql
        sleep 2
    done

    exit
fi

if [[ $ACTION == "3" ]]; then
    echo "Exiting..."
    exit
fi

clear
read -p "Application name: " APP_NAME
read -p "Application unique ID (without spaces): " APP_UID

read -p "Database name: " DB_NAME
read -p "Database user: " DB_USER
read -p "Database password: " DB_PASS

read -p "Port for Tribe: " TRIBE_PORT
read -p "Port for Junction: " JUNCTION_PORT

read -p "Junction password: " JUNCTION_PASS
read -p "Domain for APP: " APP_DOMAIN
read -p "Enable HTTPS for Tribe? (y/n): " ENABLE_SSL

# randomly generated secret for TRIBE_API
TRIBE_API_SECRET=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16)

DB_HOST="$APP_UID-db"
DOCKER_EXTERNAL_TRIBE_URL="localhost:$TRIBE_PORT"
DOCKER_EXTERNAL_JUNCTION_URL="localhost:$JUNCTION_PORT"

# Setup Tribe's bare and http/s urls
APP_DOMAIN=${APP_DOMAIN#http://}
APP_DOMAIN=${APP_DOMAIN#https://}

WEB_BARE_URL="tribe.$APP_DOMAIN"
JUNCTION_URL="junction.$APP_DOMAIN"

if echo "$ENABLE_SSL" | grep -iq "^y$"; then
    WEB_URL="https://$WEB_BARE_URL"
    JUNCTION_URL="https://$JUNCTION_URL"
    APP_URL="https://$APP_DOMAIN"
else
    WEB_BARE_URL="http://$WEB_BARE_URL"
    JUNCTION_URL="http://$JUNCTION_URL"
    APP_URL="http://$APP_URL"
fi

# .env file
echo ""
echo "Setting up environment for tribe"
cp .env.sample .env
sed -i "s|\$TRIBE_PORT|$TRIBE_PORT|g" .env
sed -i "s|\$JUNCTION_PORT|$JUNCTION_PORT|g" .env
sed -i "s|\$APP_NAME|$APP_NAME|g" .env
sed -i "s|\$JUNCTION_PASS|$JUNCTION_PASS|g" .env
sed -i "s|\$WEB_BARE_URL|$WEB_BARE_URL|g" .env
sed -i "s|\$APP_URL|$APP_URL|g" .env
sed -i "s|\$WEB_URL|$WEB_URL|g" .env
sed -i "s|\$JUNCTION_URL|$JUNCTION_URL|g" .env
sed -i "s|\$APP_UID|$APP_UID|g" .env
sed -i "s|\$DOCKER_EXTERNAL_TRIBE_URL|$DOCKER_EXTERNAL_TRIBE_URL|g" .env
sed -i "s|\$DOCKER_EXTERNAL_JUNCTION_URL|$DOCKER_EXTERNAL_JUNCTION_URL|g" .env
sed -i "s|\$DB_NAME|$DB_NAME|g" .env
sed -i "s|\$DB_USER|$DB_USER|g" .env
sed -i "s|\$DB_PASS|$DB_PASS|g" .env
sed -i "s|\$DB_HOST|$DB_HOST|g" .env
sed -i "s|\$TRIBE_API_SECRET|$TRIBE_API_SECRET|g" .env

# PHPmyadmin config update
sed -i "s|\$DB_HOST|$DB_HOST|g" config/phpmyadmin/config.inc.php

bash ./install/docker-scripts/setup-network.sh

echo "Done"
